apiVersion: apps/v1
kind: Deployment
metadata:
  name: tjmk-hospital-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /tjmk-openapi
            - name: BASE_URL
              value: /tjmk-openapi-ui