apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: martinkacani/hospital-ufe
  newName: martinkacani/hospital-ufe
  newTag: 1.2.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: martinkacani/hospital-wl-webapi
  newName: martinkacani/hospital-wl-webapi
  newTag: 1.2.0