apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: tjmk-hospital # napr. <pfx>-ambulance-wl
spec:
  title: Zoznam čakajúcich tjmk # napr. "Zoznam čakajúcich <pfx>"
  description: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Tomáš Jágerský, Martin Kačáni" # Zadajte mená autorov
  azureLink: ""
  frontendRepoUrl: "https://github.com/MartinKacani/hospital-ufe"
  backendRepoUrl: "https://github.com/MartinKacani/hospital-webapi"
  gitopsRepoUrl: "https://github.com/MartinKacani/hospital-gitops"