apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: martinkacani/hospital-ufe
  newName: martinkacani/hospital-ufe # {"$imagepolicy":  "wac-hospital-project:hospital-ufe:name"}
  newTag: main.20260403.1552 # {"$imagepolicy": "wac-hospital-project:hospital-ufe:tag"}
