apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: tjmk-hospital-ufe-content
spec:
  microFrontend: tjmk-hospital-ufe
  element: tjmk-hospital-wl-app
  attributes:
    - name: base-path
      value: /tjmk-hospital-wl/
    - name: api-base
      value: /tjmk-api
    - name: hospital-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?tjmk-hospital-wl(/.*)?$"