apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: tjmk-hospital-ufe-content
spec:
  microFrontend: tjmk-hospital-ufe
  element: tjmk-medbed-app
  attributes:
    - name: base-path
      value: /tjmk-medbed/
    - name: api-base
      value: /tjmk-api
    - name: department-id
      value: cardiology
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?tjmk-medbed(/.*)?$"